@baseUrl = http://localhost:5050

### Sign up
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
	"fullName": "Test User",
	"email": "test.user+1@gmail.com",
	"password": "123456"
}

### Sign in
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
	"email": "test.user+1@gmail.com",
	"password": "123456"
}
