@baseUrl = http://localhost:5050
@email = lnduy232@clc.fitus.edu.vn
@otp = 196785
@newPassword = 123456

### 1. Gui OTP quen mat khau
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "{{email}}"
}

### 2. Dat lai mat khau bang OTP trong email
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "email": "{{email}}",
  "otp": "{{otp}}",
  "newPassword": "{{newPassword}}"
}

### 3. Test OTP sai
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "email": "{{email}}",
  "otp": "000000",
  "newPassword": "{{newPassword}}"
}

