# ======================== Get =========================
GET http://localhost:4000/toeic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM

### Get Toeic
GET http://localhost:4000/toeic/e9c6b5eb-430b-47dd-b6de-8e700e8ea861

### Get Toeic Part 5 Questions
GET http://localhost:4000/toeic/reading-part-5-questions/fbc04e83-d751-4cfe-a97a-18ee38c38f5b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM

# ======================== Create =========================
### Create Toeic
POST http://localhost:4000/toeic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM

{
    "title": "Toeic Test 1",
    "description": "This is a sample Toeic test",
    "level": "BEGINNER"
}

### Create Toeic Part 5 Questions
POST http://localhost:4000/toeic/reading-part-5-questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM

[
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "When filling out the order form, please _____ your address clearly to prevent delays.",
        "options": [
            "fix",
            "write",
            "send",
            "direct"
        ],
        "answer": 1
    }, 
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "Ms. Morgan recruited the individuals that the company _____ for the next three months.",
        "options": [
            "will employ",
            "to employ",
            "has been employed",
            "employ"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The contractor had a fifteen-percent _____ in his business after advertising in the local newspaper.",
        "options": [
            "experience",
            "growth",
            "formula",
            "incentive"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The free clinic was founded by a group of doctors to give _____ for various medical conditions.",
        "options": [
            "treatment",
            "treat",
            "treated",
            "treating"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "Participants in the walking tour should gather _____ 533 Bates Road on Saturday morning.",
        "options": [
            "with",
            "at",
            "like",
            "among"
        ],
        "answer": 1
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The figures that accompany the financial statement should be _____ to the spending category.",
        "options": [
            "relevance",
            "relevantly",
            "more relevantly",
            "relevant"
        ],
        "answer": 3
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The building owner purchased the property _____ three months ago, but she has already spent a great deal of money on renovations.",
        "options": [
            "yet",
            "just",
            "few",
            "still"
        ],
        "answer": 1
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "We would like to discuss this problem honestly and _____ at the next staff meeting.",
        "options": [
            "rarely",
            "tiredly",
            "openly",
            "highly"
        ],
        "answer": 2
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The store’s manager plans to put the new merchandise on display _____ to promote the line of fall fashions.",
        "options": [
            "soon",
            "very",
            "that",
            "still"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "_____ that the insulation has been replaced, the building is much more energy-efficient.",
        "options": [
            "Now",
            "For",
            "As",
            "Though"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "Mr. Sims needs a more _____ vehicle for commuting from his suburban home to his office downtown.",
        "options": [
            "expressive",
            "reliable",
            "partial",
            "extreme"
        ],
        "answer": 1
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The company _____ lowered its prices to outsell its competitors and attract more customers.",
        "options": [
            "strategy",
            "strategically",
            "strategies",
            "strategic"
        ],
        "answer": 1
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": " _____ Mr. Williams addressed the audience, he showed a brief video about the engine he had designed.",
        "options": [
            "Then",
            "So that",
            "Before",
            "Whereas"
        ],
        "answer": 2
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "For optimal safety on the road, avoid _____ the view of the rear window and side-view mirrors.",
        "options": [
            "obstructs",
            "obstructed",
            "obstruction",
            "obstructing"
        ],
        "answer": 3
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "Having proper ventilation throughout the building is _____ for protecting the health and well-being of the workers.",
        "options": [
            "cooperative",
            "visible",
            "essential",
            "alternative"
        ],
        "answer": 2
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "_____ sales of junk food have been steadily declining indicates that consumers are becoming more health-conscious.",
        "options": [
            "In addition to",
            "The fact that",
            "As long as",
            "In keeping with"
        ],
        "answer": 1
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The sprinklers for the lawn’s irrigation system are _____ controlled.",
        "options": [
            "mechanically",
            "mechanic",
            "mechanism",
            "mechanical"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The library staff posted signs to _____ patrons of the upcoming closure for renovations.",
        "options": [
            "notify",
            "agree",
            "generate",
            "perform"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "Mr. Ross, _____ is repainting the interior of the lobby, was recommended by a friend of the building manager.",
        "options": [
            "himself",
            "he",
            "who",
            "which"
        ],
        "answer": 2
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The guidelines for the monthly publication are _____ revised to adapt to the changing readers.",
        "options": [
            "courteously",
            "initially",
            "periodically",
            "physically"
        ],
        "answer": 2
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "_____ an ankle injury, the baseball player participated in the last game of the season.",
        "options": [
            "In spite of",
            "Even if",
            "Whether",
            "Given that"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The governmental department used to provide financial aid, but now it offers _____ services only.",
        "options": [
            "legal",
            "legalize",
            "legally",
            "legalizes"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "At the guest’s _____ , an extra set of towels and complimentary soaps were brought to the room.",
        "options": [
            "quote",
            "graduation",
            "request",
            "dispute"
        ],
        "answer": 2
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The upscale boutique Jane’s Closet is known for selling the most stylish _____ for young professionals.",
        "options": [
            "accessorized",
            "accessorize",
            "accessorizes",
            "accessories"
        ],
        "answer": 3
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The company started to recognize the increasing _____ of using resources responsibly.",
        "options": [
            "more important",
            "importantly",
            "importance",
            "important"
        ],
        "answer": 2
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "_____ restructuring several departments within the company, the majority of the problems with miscommunication have disappeared.",
        "options": [
            "After",
            "Until",
            "Below",
            "Like"
        ],
        "answer": 0
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "The riskiest _____ of the development of new medications are the trials with human subjects.",
        "options": [
            "proceeds",
            "perspectives",
            "installments",
            "stages"
        ],
        "answer": 3 
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": " _____ seeking a position at Tulare Designs must submit a portfolio of previous work.",
        "options": [
            "Anyone",
            "Whenever",
            "Other",
            "Fewer"
        ],
        "answer": 0
    }
]

### Create Toeic Part 6 Questions
POST http://localhost:4000/toeic/reading-part-6-questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM

[
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "<p><strong>To:</strong> samsmith@digitalIT.com</p><p><strong>From:</strong> sharronb@email.com</p><p><strong>Date:</strong> September 24</p><p><strong>Subject:</strong> Business Contract</p><p>Dear Mr. Smith,</p><p>I am Sharron Biggs, CEO and founder of Biggs Graphics. I recently came across your advertisement <strong>(131)</strong> the partnership of a graphic design company for a number of your projects.</p><p>Biggs Graphics has <strong>(132)</strong> experience working with various small businesses and companies in designing advertising campaigns, logos, and websites.</p><p><strong>(133)</strong> Our website www.biggs-graphics.com also has some information about our company.</p><p>I'm interested in working with your company on your projects and hope we can build a beneficial partnership. I look forward <strong>(134)</strong> your reply.</p><p>Sincerely,</p><p>Sharron Biggs</p><p><strong>CEO, Biggs Graphics</strong></p>",
        "options": [
            {
                "title": 131,
                "options": [
                    "seek",
                    "to seek",
                    "seeking",
                    "are seeking"
                ],
                "answer": 2
            },
            {
                "title": 132,
                "options": [
                    "extensive",
                    "restricted",
                    "generous",
                    "limitless"
                ],
                "answer": 0
            }, 
            {
                "title": 133,
                "options": [
                    "I would really appreciate the opportunity to work with you.",
                    "I heard that DigitalIT is a great company.",
                    "In fact, our designs are often copied by other companies.",
                    "I have attached a number of our past designs to illustrate what we specialize in."
                ],
                "answer": 3
            },
            {
                "title": 134,
                "options": [
                    "at",
                    "to",
                    "with",
                    "from"
                ],
                "answer": 1
            }
        ]
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "Thank you for shopping at Larson''s China. Our products are known for their modern and unique patterns and color combinations, as well as ___(135)___ and strength. ___(136)___ Please note, however, that repeated drops and rough handling will ___(137)___ eventual breakage. We suggest you store them carefully and that you don''t use harsh chemicals, steel sponges, or ___(138)___ scrubbing when cleaning them. Please visit our website at www.larsonchina.com for information about handling and care or call us at 555-1234 if you have any questions or concerns.",
        "options": [
            {
                "title": 135,
                "options": [
                    "durable",
                    "durability",
                    "durableness",
                    "nondurable"
                ],
                "answer": 1
            },
            {
                "title": 136,
                "options": [
                    "Larson's utensils and silverware go great with the dinnerware.",
                    "Our most popular line, the Spring Flower China, is sold out at most locations.",
                    "Visit our store to check out our other beautiful products.",
                    "They are dishwasher - and microwave-safe and we're confident that you'll be using them for years to come."
                ],
                "answer": 3
            },
            {
                "title": 137,
                "options": [
                    "result in",
                    "occur to",
                    "ending at",
                    "stop with"
                ],
                "answer": 0
            },
            {
                "title": 138,
                "options": [
                    "ambitious",
                    "combative",
                    "aggressive",
                    "complacent"
                ],
                "answer": 2
            }
        ]
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "<p><strong>Entry Position: Gold &amp; Slide Accounting Firm</strong> <div/> We are looking for enthusiastic candidates with an educational background in finance or ___(139)___. All candidates should have some computer experience. Job experience is not ___(140)___ but preferred. Candidates with a bilingual language ability ___(141)___ favored. Positions include jobs in accounting, statistics, and general office assistant. If you are interested, please visit our website at www.G&amp;Saccountingfirm.com/employment for more information. You can send your cover letters and resumes to Karen Hill at khill@G&amp;S.com. We will begin interviewing candidates on Monday, November 5. ___(142)___</p>",
        "options": [
            {
                "title": 139,
                "options": [
                    "account",
                    "accountant",
                    "accounting",
                    "accounted"
                ],
                "answer": 2
            },
            {
                "title": 140,
                "options": [
                    "basic",
                    "decisive",
                    "additional",
                    "necessary"
                ],
                "answer": 3
            },
            {
                "title": 141,
                "options": [
                    "is being",
                    "will be",
                    "has been",
                    "were being"
                ],
                "answer": 1
            },
            {
                "title": 142,
                "options": [
                    "We sincerely thank you for your interest.",
                    "The positions begin the following month.",
                    "Please call us for more information.",
                    "We apologize for any inconvenience."
                ],
                "answer": 1
            }
        ]
    },
    {
        "toeicId": "fbc04e83-d751-4cfe-a97a-18ee38c38f5b",
        "question": "<p><strong>To:</strong> Kitchen staff, office employees<br><strong>From:</strong> Manager, Larry Park<br><strong>Date:</strong> March 23<br><strong>Subject:</strong> Renovations</p><p>To all kitchen staff and Harmon employees,</p><p>From Sunday, March 23 to Thursday, March 27, the employee cafeteria kitchens will undergo renovations as new appliances and equipment ___(143)___ in to replace the old ones. ___(144)___ Instead, the convenience shops will carry more sandwiches, prepared lunch boxes, and snacks for the employees during this time.</p><p>The renovations will increase the number of sinks, ovens, and stove tops so that a larger volume of meals can be provided ___(145)___ the lunch and dinner rushes. We apologize for the inconvenience but we hope that the changes will ___(146)___ the services in the cafeteria.</p>",
        "options": [
            {
                "title": 143,
                "options": [
                    "are bringing",
                    "have brought",
                    "bring",
                    "are brought"
                ],
                "answer": 3
            },
            {
                "title": 144,
                "options": [
                    "This will take a lot of work.",
                    "As a result, the convenience shops will be closed.",
                    "Because of this, hot meals will not be available for the patrons.",
                    "There will be noise and chaos as a result."
                ],
                "answer": 2
            },
            {
                "title": 145,
                "options": [
                    "before",
                    "after",
                    "during",
                    "within"
                ],
                "answer": 2
            },
            {
                "title": 146,
                "options": [
                    "develop",
                    "improve",
                    "rectify",
                    "recover"
                ],
                "answer": 1
            }
        ]
    }
]

# ======================== Update =========================
### Update Toeic
PUT http://localhost:4000/toeic/e9c6b5eb-430b-47dd-b6de-8e700e8ea861
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM

{
    "title": "Toeic Test 1 Updated",
    "description": "This is an updated sample Toeic test",
    "level": "INTERMEDIATE"
}

### Update Toeic Part 5 Question
PUT http://localhost:4000/toeic/reading-part-5-questions/a36a11a8-8254-422c-90a3-daf7cf592dd5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM

{
    "question": "When filling out the order form, please _____ your address clearly to prevent delays.",
    "options": [
        "fix",
        "write",
        "send",
        "direct"
    ],
    "answer": 1
}


# ======================== Delete =========================
### Delete Toeic
DELETE http://localhost:4000/toeic/e9c6b5eb-430b-47dd-b6de-8e700e8ea861
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmZhMjRjZC0yODQ3LTQ1YTUtYTQzZC0zMDE5MDZmNDE1NmQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc3NjM5NTczMiwiZXhwIjoxNzc2NDgyMTMyfQ.j2X5GaSQNeHK0WE01stKbIugX4aVsp9ig-FhJNRfbMM
