package com.penguin.linguae.core.ui.theme

import androidx.compose.ui.graphics.Color

val AppBackground = Color(0xFFF4F5FA)
val SurfaceColor = Color(0xFFFFFFFF)
val TextDark = Color(0xFF1E1E2C)
val TextGray = Color(0xFF8A8A9D)
val PurpleBlueTheme = Color(0xFF5A67D8)
val SearchBg = Color(0xFFEBE8FF)
val StarActive = Color(0xFFFFC107)
val PrimaryPurple = Color(0xFF6B4EFF)
val LightPurple = Color(0xFFEBE8FF)
val IconBackground = Color(0xFFF8F8FB)

val BorderGray = Color(0xFFE0E0E0)

val PurplePrimary   = Color(0xFF6C5CE7)
val PurpleDark      = Color(0xFF4834D4)
val PurpleDeep      = Color(0xFF2C1FA8)
val PurpleLight     = Color(0xFFEDE9FB)
val PurpleMid       = Color(0xFFA89CE0)
val PurpleHint      = Color(0xFF9B93C8)
val PageBg          = Color(0xFFF0EEF9)
val BadgeBlue       = Color(0xFF1877C7)
val BadgeBlueBg     = Color(0xFFE8F4FD)
val BlueSurfaceBackground = Color(0xFFC7CCFC)
val FlashCard = Color(0xFFFFFFFF)
val Orange = Color(0xFFFF6705)
val TransparentWhite = Color(0x44FFFFFF)
val Blue = Color(0xFF25B6E3)
val Green = Color(0xFF13E01D)
val Yellow = Color(0xFFFFC900)
val Sapphire = Color(0xFF42A4F5)
val Emerald = Color(0xFF76FF5D)
val Red = Color(0xFFFF0057)
val Black = Color(0xFF000000)
val HomeHeroStart = Color(0xFF4F5DE9)
val HomeHeroMid = Color(0xFF6170F2)
val HomeHeroEnd = Color(0xFF7C4DFF)
val HomeHeroTint = Color(0x26FFFFFF)
val HomeCardBorder = Color(0x14FFFFFF)
val HomeSurfaceTint = Color(0xFFF7F6FF)